create database student;
use student;
create table Student(StdID int, StdName varchar(50));
show databases;
show tables;
select * from student.student;
desc student.student;
ALTER TABLE student.student ADD Email varchar(20) ;
alter table student.student modify Email varchar(20) NOT NULL;
alter table student.student modify StdID int not null auto_increment primary key;
ALTER TABLE student.student ADD AGE INT, ADD ADDRESS VARCHAR(50),ADD GENDER VARCHAR(10), ADD PHONENO INT;
alter table student.student drop age;
alter table student.student add Age int;
alter table student.student drop phoneno;
alter table student.student add phoneno varchar(15);
insert into student.student value(1,"surya","surya@gamil.com","Hyderabad","Male",9876543210,21);
insert into student.student value(2,"saketh","saketh@gmail.com","Eluru","male",8976543210,20);
insert into student.student value(NULL,"khasyap","khasyap@gmail.com","Vijayawada","male",7896541230,22);
update student.student set gender="Male" where stdID=2;
